### PR TITLE
Added ShapeShift and KeepKey

### PR DESCRIPTION
**Pull request by mperklin**

### CODE REVIEW

**Comment by mperklin** [comment]
(also... what I should have written first)

Thanks, Dan, for merging our PR so quickly to get our name added. We appreciate the fast action!

**Comment by dguido** [comment]
I only chopped off the word "Responsible" from "Responsible Disclosure Program." First, it's a loaded term and you should consider researching coordinated disclosure. Second, it'll keep the table tidy and consistent to use the shorter "Disclosure Program" language. It still links to the same place!

**Comment by mperklin** [comment]
uido,

You may feel the word _Responsible_ is "loaded", but that word is a part of the official name of our program.

Your name is dguido. It's not common to chop off part of your official name and call you "uido" even though it still refers to the same person.

Ultimately you're the curator of this list, and I thank you for including ShapeShift on the list even if you're using the wrong name.

**Comment by dguido** [comment]
Sure, but a calling your program a disclosure program is correct, right? I would rather not identify the specific type and details of every program from every company. At the end of the day, they are all just disclosure programs.

We’ll be in touch in a few days. Thanks for leaving your info!

**Pull request merged**
