### PR TITLE
added SALT

### PR DESCRIPTION
**Pull request by git4tomd**

### CODE REVIEW

**Comment by git4tomd** [comment]
https://saltlending.com

**Comment by jdixon-salt** [comment]
Will this be merged into the 'master' branch at some point? Or, should we submit a PR against the 'master' branch?

**Comment by dguido** [comment]
Oh, woops. Yes, please always make a PR against master. Can you make a new one? I'm going to delete this extraneous exchange-contacts branch.

**Comment by dguido** [comment]
Actually, never mind. I'll merge exchange-contacts into master.

**Pull request merged**
